Repository x1-company/be14-fin-frans-be, pull requests merged in 2025-06, with the labels that each got.

#6 ✨ feat: 주문 마감 시간 등록, 수정
  src/main/java/com/x1/frans/order/command/application/controller/StoreOrderDeadlineController.java
  src/main/java/com/x1/frans/order/command/application/service/StoreOrderDeadlineService.java
  src/main/java/com/x1/frans/order/command/application/service/StoreOrderDeadlineServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/StoreOrderDeadline.java
  src/main/java/com/x1/frans/order/command/domain/repository/OrderCommandRepository.java
  src/main/java/com/x1/frans/order/command/domain/repository/StoreOrderDeadlineRepository.java
Labels: ✨ Feature

#9 ✨feat: 로그인 기능 구현
  build.gradle
  src/main/java/com/x1/frans/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/x1/frans/auth/command/application/service/AuthCommandService.java
  src/main/java/com/x1/frans/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/x1/frans/config/JacksonConfig.java
  src/main/java/com/x1/frans/exception/ExpiredRefreshTokenException.java
  src/main/java/com/x1/frans/exception/InvalidRefreshTokenException.java
  src/main/java/com/x1/frans/exception/dto/ErrorResponseDTO.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/redis/config/RedisConfig.java
  src/main/java/com/x1/frans/redis/service/RedisService.java
  src/main/java/com/x1/frans/redis/service/RedisServiceImpl.java
  src/main/java/com/x1/frans/security/AuthenticationFilter.java
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/security/JwtAuthenticationFilter.java
  src/main/java/com/x1/frans/security/JwtAuthenticationProvider.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
  src/main/java/com/x1/frans/security/config/properties/TokenProperties.java
  src/main/java/com/x1/frans/security/exception/AccountDeletedException.java
  src/main/java/com/x1/frans/security/exception/AccountLockedException.java
  src/main/java/com/x1/frans/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/x1/frans/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/x1/frans/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/security/vo/RequestLoginVO.java
  src/main/java/com/x1/frans/user/query/repository/UserQueryMapper.java
  src/main/java/com/x1/frans/user/query/service/UserQueryService.java
  src/main/java/com/x1/frans/user/query/service/UserQueryServiceImpl.java
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: ✨ Feature

#13 ✨ feat: Swagger 설정 추가 및 API 문서화 적용
  build.gradle
  gradlew
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/order/command/application/controller/StoreOrderDeadlineController.java
Labels: 📚 Docs, ✨ Feature

#11 ✨ feat: 비밀번호 변경
  src/main/java/com/x1/frans/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/x1/frans/auth/command/application/vo/ChangePasswordRequestVO.java
  src/main/java/com/x1/frans/exception/InvalidPasswordException.java
  src/main/java/com/x1/frans/exception/UserNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/user/command/repository/UserCommandRepository.java
  src/main/java/com/x1/frans/user/command/service/UserCommandService.java
  src/main/java/com/x1/frans/user/command/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#20 ✨ feat : 공급처 상세 조회
  src/main/java/com/x1/frans/supplier/query/controller/SupplierQueryController.java
  src/main/java/com/x1/frans/supplier/query/dto/SupplierDetailDTO.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierQueryMapper.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierQueryService.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierQueryServiceImpl.java
  src/main/resources/com/x1/frans/supplier/query/repository/SupplierQueryMapper.xml
Labels: ✨ Feature

#16 🚑 fix: Swagger LocalTime 형식 오류 해결 및 예외 처리 추가
  src/main/java/com/x1/frans/exception/DuplicateDeadlineTimeException.java
  src/main/java/com/x1/frans/exception/InvalidTimeFormatException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/controller/StoreOrderDeadlineController.java
  src/main/java/com/x1/frans/order/command/application/service/StoreOrderDeadlineServiceImpl.java
Labels: ✨ Feature, 🐛 Fix

#35 🔨 refactor: id 타입 long으로 변경
  src/main/java/com/x1/frans/franchise/command/aggregate/FranchiseEntity.java
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/supplier/command/application/controller/SupplierCommandController.java
  src/main/java/com/x1/frans/supplier/command/application/service/SupplierCommandService.java
  src/main/java/com/x1/frans/supplier/command/application/service/SupplierCommandServiceImpl.java
  src/main/java/com/x1/frans/supplier/command/domain/aggregate/SupplierEntity.java
  src/main/java/com/x1/frans/supplier/command/domain/repository/SupplierCommandRepository.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierQueryController.java
  src/main/java/com/x1/frans/user/command/aggregate/HqUserDetailEntity.java
  src/main/java/com/x1/frans/user/command/aggregate/UserEntity.java
  src/main/java/com/x1/frans/user/command/controller/UserCommandController.java
  src/main/java/com/x1/frans/user/command/repository/HqUserDetailCommandRepository.java
  src/main/java/com/x1/frans/user/command/repository/UserCommandRepository.java
  src/main/java/com/x1/frans/user/command/service/UserCommandService.java
  src/main/java/com/x1/frans/user/command/service/UserCommandServiceImpl.java
  src/main/java/com/x1/frans/user/command/vo/FranchiseUserRequestVO.java
  src/main/java/com/x1/frans/user/command/vo/HqUserRequestVO.java
  src/main/java/com/x1/frans/user/command/vo/SupplierUserRequestVO.java
Labels: 🔨 Refactor

#34 ✨ feat: 본사용 주문 목록 조회 및 필터 기능 구현
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/order/command/application/controller/StoreOrderDeadlineController.java
  src/main/java/com/x1/frans/order/query/controller/OrderQueryController.java
  src/main/java/com/x1/frans/order/query/dao/OrderQueryMapper.java
  src/main/java/com/x1/frans/order/query/dto/OrderSearchConditionDto.java
  src/main/java/com/x1/frans/order/query/dto/OrderSearchPageResponseDto.java
  src/main/java/com/x1/frans/order/query/dto/OrderSummaryResponseDto.java
  src/main/java/com/x1/frans/order/query/service/OrderQueryService.java
  src/main/java/com/x1/frans/order/query/service/OrderQueryServiceImpl.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierQueryController.java
  src/main/resources/com/x1/frans/order/query/dao/OrderQueryMapper.xml
Labels: ✨ Feature

#37 ✨ feat: 로그아웃 기능 구현
  src/main/java/com/x1/frans/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/x1/frans/auth/command/application/service/AuthCommandService.java
  src/main/java/com/x1/frans/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/x1/frans/security/AuthenticationFilter.java
  src/main/java/com/x1/frans/security/JwtAuthenticationFilter.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/user/command/service/UserCommandService.java
  src/main/java/com/x1/frans/user/command/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#39 🔨 refactor: int -> long 변경
  src/main/java/com/x1/frans/supplier/command/application/controller/SupplierCommandController.java
  src/main/java/com/x1/frans/supplier/command/vo/SupplierUpdateRequestVO.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierQueryController.java
  src/main/java/com/x1/frans/supplier/query/dto/SupplierDetailDTO.java
  src/main/java/com/x1/frans/supplier/query/dto/SupplierListDTO.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierQueryMapper.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierQueryService.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierQueryServiceImpl.java
  src/main/java/com/x1/frans/user/query/controller/UserQueryController.java
  src/main/java/com/x1/frans/user/query/dto/SearchHqUserDTO.java
  src/main/java/com/x1/frans/user/query/repository/UserQueryMapper.java
  src/main/java/com/x1/frans/user/query/service/UserQueryService.java
  src/main/java/com/x1/frans/user/query/service/UserQueryServiceImpl.java
Labels: 🔨 Refactor

#43 ✨ feat: 개발용 cors 설정
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
Labels: ✨ Feature

#55 ✨ feat: 본사 직원 부서 정보 조회
  src/main/java/com/x1/frans/user/query/controller/UserQueryController.java
  src/main/java/com/x1/frans/user/query/dto/HqUserDepartmentDTO.java
  src/main/java/com/x1/frans/user/query/repository/UserQueryMapper.java
  src/main/java/com/x1/frans/user/query/service/UserQueryService.java
  src/main/java/com/x1/frans/user/query/service/UserQueryServiceImpl.java
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: ✨ Feature

#56 🚑 fix: 가맹점 정보 업데이트 시 접근 권한 체크하도록 수정
  src/main/java/com/x1/frans/exception/UnauthorizedAccessException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/franchise/command/application/controller/FranchiseCommandController.java
  src/main/java/com/x1/frans/franchise/command/application/service/FranchiseCommandServiceImpl.java
  src/main/java/com/x1/frans/franchise/command/domain/aggregate/FranchiseEntity.java
  src/main/java/com/x1/frans/returns/query/dto/ShippedOrderDTO.java
  src/main/java/com/x1/frans/user/command/vo/FranchiseUserRequestVO.java
  src/main/resources/com/x1/frans/returns/query/repository/ReturnQueryMapper.xml
Labels: 🚑 Fix

#50 ✨ feat: 창고 등록
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/warehouse/command/application/controller/WarehouseCommandController.java
  src/main/java/com/x1/frans/warehouse/command/application/service/WarehouseCommandService.java
  src/main/java/com/x1/frans/warehouse/command/application/service/dto/WarehouseCreateCommand.java
  src/main/java/com/x1/frans/warehouse/command/domain/aggregate/WarehouseEntity.java
  src/main/java/com/x1/frans/warehouse/command/domain/repository/WarehouseRepository.java
Labels: ✨ Feature

#58 ✨ feat: 자재 조회 기능 구현
  src/main/java/com/x1/frans/exception/ProductNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/product/query/controller/ProductQueryController.java
  src/main/java/com/x1/frans/product/query/dto/ProductDetailDTO.java
  src/main/java/com/x1/frans/product/query/dto/ProductListDTO.java
  src/main/java/com/x1/frans/product/query/repository/ProductQueryMapper.java
  src/main/java/com/x1/frans/product/query/service/ProductQueryService.java
  src/main/java/com/x1/frans/product/query/service/ProductQueryServiceImpl.java
  src/main/resources/com/x1/frans/product/query/repository/ProductQueryMapper.xml
Labels: ✨ Feature

#53 ✨ feat: 가맹점 목록 조회 추가 구현
  src/main/java/com/x1/frans/franchise/query/controller/FranchiseQueryController.java
  src/main/java/com/x1/frans/franchise/query/dto/FranchiseListDTO.java
  src/main/java/com/x1/frans/franchise/query/repository/FranchiseQueryMapper.java
  src/main/java/com/x1/frans/franchise/query/service/FranchiseQueryService.java
  src/main/java/com/x1/frans/franchise/query/service/FranchiseQueryServiceImpl.java
  src/main/resources/com/x1/frans/franchise/query/repository/FranchiseQueryMapper.xml
Labels: ✨ Feature, 🔨 Refactor

#61 ✨ feat: 가맹점 api 경로 수정 및 가맹점 목록 조회 예외 추가
  src/main/java/com/x1/frans/franchise/query/controller/FranchiseQueryController.java
Labels: ✨ Feature, 🔨 Refactor

#69 ✨ feat: 주문 반려 기능 구현
  src/main/java/com/x1/frans/exception/InvalidOrderRejectConditionException.java
  src/main/java/com/x1/frans/exception/OrderNotFoundException.java
  src/main/java/com/x1/frans/exception/OrderRejectReasonRequiredException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/controller/HqOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/controller/StoreOrderDeadlineController.java
  src/main/java/com/x1/frans/order/command/application/dto/OrderRejectRequestDto.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/application/service/StoreOrderDeadlineServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Delivery.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/StoreOrderDeadline.java
  src/main/java/com/x1/frans/order/command/domain/repository/OrderCommandRepository.java
  src/main/java/com/x1/frans/order/command/domain/repository/StoreOrderDeadlineRepository.java
Labels: ✨ Feature

#77 ✨ feat: 주문 상태를 검토 완료로 변경
  src/main/java/com/x1/frans/order/command/application/controller/HqOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
Labels: ✨ Feature

#83 🔨 refactor: token에 부서, 직책, 직급 정보 추가
  src/main/java/com/x1/frans/auth/command/application/vo/ChangePasswordRequestVO.java
  src/main/java/com/x1/frans/auth/command/application/vo/ResetPasswordRequestVO.java
  src/main/java/com/x1/frans/security/AuthenticationFilter.java
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/security/vo/RequestLoginVO.java
  src/main/java/com/x1/frans/user/command/vo/CreateUserRequestVO.java
  src/main/java/com/x1/frans/user/command/vo/FranchiseUserRequestVO.java
  src/main/java/com/x1/frans/user/command/vo/HqUserRequestVO.java
  src/main/java/com/x1/frans/user/command/vo/SupplierUserRequestVO.java
  src/main/java/com/x1/frans/user/query/dto/LoginUserDTO.java
  src/main/java/com/x1/frans/user/query/repository/UserQueryMapper.java
  src/main/java/com/x1/frans/user/query/service/UserQueryServiceImpl.java
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: 🔨 Refactor

#82 ✨ feat: 주문 상태 관리를 위한 OrderStatus enum 정의
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/vo/OrderStatus.java
Labels: ✨ Feature, 🔨 Refactor

#85 ✨ feat: 검토 취소하여 주문 상태를 검토 중으로 변경
  src/main/java/com/x1/frans/order/command/application/controller/HqOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
Labels: ✨ Feature

#95 ✨ feat: 가맹점 주문 금액 통계 조회 기능 구현
  src/main/java/com/x1/frans/exception/StatisticsUnauthorizedAccessException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/statistics/query/view/controller/FranchiseOrderAmountQueryController.java
  src/main/java/com/x1/frans/statistics/query/view/dto/FranchiseOrderAmountQueryDTO.java
  src/main/java/com/x1/frans/statistics/query/view/repository/FranchiseOrderAmountMapper.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseOrderAmountQueryService.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseOrderAmountQueryServiceImpl.java
  src/main/resources/com/x1/frans/statistics/query/view/repository/FranchiseOrderAmountMapper.xml
Labels: ✨ Feature

#102 ✨ feat: 주문 배송 상태 변경
  src/main/java/com/x1/frans/order/command/application/controller/HqOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/dto/OrderStatusUpdateRequestDto.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/vo/DeliveryStatus.java
Labels: ✨ Feature

#106 ✨ feat: 배송 정보 등록, 수정 구현
  src/main/java/com/x1/frans/order/command/application/controller/HqOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/dto/DeliveryInfoRequestDto.java
  src/main/java/com/x1/frans/order/command/application/dto/OrderStatusUpdateRequestDto.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Delivery.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/repository/DeliveryRepository.java
  src/main/java/com/x1/frans/order/command/domain/vo/OrderStatus.java
  src/main/java/com/x1/frans/user/enums/DeliveryStatus.java
Labels: ✨ Feature

#97 ✨ feat: 가맹점 자재별 반품량 통계 조회 기능 구현
  src/main/java/com/x1/frans/statistics/query/view/controller/FranchiseReturnProductQueryController.java
  src/main/java/com/x1/frans/statistics/query/view/dto/FranchiseReturnProductQueryDTO.java
  src/main/java/com/x1/frans/statistics/query/view/repository/FranchiseReturnProductMapper.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseReturnProductQueryService.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseReturnProductQueryServiceImpl.java
  src/main/resources/com/x1/frans/statistics/query/view/repository/FranchiseReturnProductMapper.xml
Labels: ✨ Feature

#99 ✨ feat: 계정 생성 시 부서, 직급 제한 추가
  src/main/java/com/x1/frans/exception/AccessDeniedException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/user/command/controller/UserCommandController.java
  src/main/java/com/x1/frans/user/enums/DepartmentType.java
  src/main/java/com/x1/frans/user/enums/DutyType.java
  src/main/java/com/x1/frans/user/enums/PositionType.java
Labels: ✨ Feature

#108 ✨ feat: 가맹점용 주문 취소 구현
  src/main/java/com/x1/frans/exception/OrderDeadlineTimeNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/controller/FranchiseOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/service/FranchiseOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/FranchiseOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/common/OrderAuthorizationService.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
Labels: ✨ Feature

#100 ✨ feat: 결재 등록 기능
  src/main/java/com/x1/frans/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalCreateRequestDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalCreateResponseDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalDocumentDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalFileDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalLineRequestDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/CommonResponse.java
  src/main/java/com/x1/frans/approval/command/application/service/ApprovalCommandService.java
  src/main/java/com/x1/frans/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/ApprovalEntity.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/ApprovalFileEntity.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/ApprovalLineEntity.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/OrderApprovalEntity.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/PurchaseOrderApprovalEntity.java
  src/main/java/com/x1/frans/approval/command/domain/aggregate/ReturnApprovalEntity.java
  src/main/java/com/x1/frans/approval/command/domain/repository/ApprovalCommandRepository.java
  src/main/java/com/x1/frans/approval/command/domain/repository/ApprovalFileCommandRepository.java
  src/main/java/com/x1/frans/approval/command/domain/repository/ApprovalLineCommandRepository.java
  src/main/java/com/x1/frans/approval/command/domain/repository/OrderApprovalCommandRepository.java
  src/main/java/com/x1/frans/approval/command/domain/repository/PurchaseOrderApprovalCommandRepository.java
  src/main/java/com/x1/frans/approval/command/domain/repository/ReturnApprovalCommandRepository.java
  src/main/java/com/x1/frans/approval/common/ApprovalCategoryType.java
  src/main/java/com/x1/frans/approval/common/ApprovalLineStatus.java
  src/main/java/com/x1/frans/approval/common/ApprovalLineType.java
  src/main/java/com/x1/frans/approval/common/ApprovalStatus.java
  src/main/java/com/x1/frans/approval/query/repository/ApprovalQueryMapper.java
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryService.java
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/java/com/x1/frans/supplier/command/application/controller/SupplierCommandController.java
  src/main/resources/com/x1/frans/approval/query/repository/ApprovalQueryMapper.xml
Labels: ✨ Feature

#105 ✨ feat: 출고 로직 생성
  src/main/java/com/x1/frans/exception/OutboundNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/repository/OrderCommandRepository.java
  src/main/java/com/x1/frans/outbound/command/application/controller/OutboundCommandController.java
  src/main/java/com/x1/frans/outbound/command/application/service/OutboundCommandService.java
  src/main/java/com/x1/frans/outbound/command/application/service/OutboundCommandServiceImpl.java
  src/main/java/com/x1/frans/outbound/command/application/vo/RegisterOutboundInfoVO.java
  src/main/java/com/x1/frans/outbound/command/domain/aggregate/OrderOutboundEntity.java
  src/main/java/com/x1/frans/outbound/command/domain/aggregate/OutboundEntity.java
  src/main/java/com/x1/frans/outbound/command/domain/repository/OrderOutboundCommandRepository.java
  src/main/java/com/x1/frans/outbound/command/domain/repository/OutBoundCommandRepository.java
Labels: ✨ Feature

#112 🚑 fix: 본사용 주문 목록 조회시 권한 누락 수정
  src/main/java/com/x1/frans/order/query/controller/FranchiseOrderQueryController.java
  src/main/java/com/x1/frans/order/query/controller/HqOrderQueryController.java
  src/main/java/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.java
  src/main/java/com/x1/frans/order/query/dto/OrderSearchConditionDto.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryService.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/user/command/service/UserCommandServiceImpl.java
  src/main/java/com/x1/frans/user/query/repository/UserQueryMapper.java
  src/main/java/com/x1/frans/user/query/service/UserQueryService.java
  src/main/java/com/x1/frans/user/query/service/UserQueryServiceImpl.java
  src/main/resources/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.xml
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: 🚑 Fix

#117 ✨ feat: 반품 정보 등록 기능 구현
  build.gradle
  src/main/java/com/x1/frans/aws/controller/AmazonS3Controller.java
  src/main/java/com/x1/frans/aws/service/AmazonS3Service.java
  src/main/java/com/x1/frans/config/AwsConfig.java
  src/main/java/com/x1/frans/exception/AwsFIleUploadException.java
  src/main/java/com/x1/frans/exception/InvalidFilUploadTypeException.java
  src/main/java/com/x1/frans/exception/InvalidFileExtensionException.java
  src/main/java/com/x1/frans/exception/InvalidReturnArgumentException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/franchise/command/application/controller/HqFranchiseCommandController.java
  src/main/java/com/x1/frans/franchise/command/application/service/FranchiseCommandService.java
  src/main/java/com/x1/frans/franchise/command/application/service/FranchiseCommandServiceImpl.java
  src/main/java/com/x1/frans/franchise/command/domain/aggregate/FranchiseEntity.java
  src/main/java/com/x1/frans/franchise/command/domain/repository/FranchiseCommandRepository.java
  src/main/java/com/x1/frans/returns/command/application/controller/ReturnCommandController.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandService.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandServiceImpl.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnDetailEntity.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnEntity.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnFileEntity.java
  src/main/java/com/x1/frans/returns/command/domain/repository/ReturnCommandRepository.java
  src/main/java/com/x1/frans/returns/command/domain/repository/ReturnDetailCommandRepository.java
  src/main/java/com/x1/frans/returns/command/domain/repository/ReturnFileCommandRepository.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnCreateRequestVO.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnDetailRequestVO.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnFileRequestVO.java
  src/main/java/com/x1/frans/returns/enums/ProductReturnStatus.java
  src/main/java/com/x1/frans/returns/enums/ReturnReasonType.java
  src/main/java/com/x1/frans/returns/query/controller/ReturnQueryController.java
  src/main/java/com/x1/frans/returns/query/dto/ProductOrderDTO.java
  src/main/java/com/x1/frans/returns/query/dto/ShippedOrderDTO.java
  src/main/java/com/x1/frans/returns/query/repository/ReturnQueryMapper.java
  src/main/java/com/x1/frans/returns/query/service/ReturnQueryService.java
  src/main/java/com/x1/frans/returns/query/service/ReturnQueryServiceImpl.java
  src/main/resources/com/x1/frans/returns/query/repository/ReturnQueryMapper.xml
Labels: ✨ Feature

#113 ✨ feat: 가맹점 별 자재 주문량 통계
  src/main/java/com/x1/frans/statistics/command/application/generator/FranchiseProductOrderStatGenerator.java
  src/main/java/com/x1/frans/statistics/command/domain/aggregate/FranchiseProductOrderStat.java
  src/main/java/com/x1/frans/statistics/command/domain/repository/FranchiseProductOrderStatRepository.java
  src/main/java/com/x1/frans/statistics/query/view/controller/FranchiseProductOrderQueryController.java
  src/main/java/com/x1/frans/statistics/query/view/dto/FranchiseProductOrderQueryDTO.java
  src/main/java/com/x1/frans/statistics/query/view/repository/FranchiseProductOrderMapper.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseProductOrderQueryService.java
  src/main/java/com/x1/frans/statistics/query/view/service/FranchiseProductOrderQueryServiceImpl.java
  src/main/resources/com/x1/frans/statistics/query/view/repository/FranchiseProductOrderMapper.xml
Labels: ✨ Feature

#121 ✨ feat: 주문 마감 시간 이후 주문 일괄 전송 구현
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/scheduler/OrderStatusScheduler.java
  src/main/java/com/x1/frans/order/command/application/service/HqOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/repository/OrderCommandRepository.java
  src/main/java/com/x1/frans/order/query/dao/StoreOrderDeadlineQueryMapper.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnEntity.java
Labels: ✨ Feature

#120 🔨 fix: 누락된 주입 추가
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/resources/com/x1/frans/approval/query/repository/ApprovalQueryMapper.xml
Labels: ✨ Feature

#122 🚑 fix: 의존성 수정, Order 엔티티 수정
  build.gradle
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
Labels: ✨ Feature

#115 ✨ feat: 결재선 사용자 결정(승인/반려) 기능 구현
  src/main/java/com/x1/frans/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalApproveRequestDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalRejectRequestDTO.java
  src/main/java/com/x1/frans/approval/command/application/dto/ApprovalResponseDTO.java
  src/main/java/com/x1/frans/approval/command/application/service/ApprovalCommandService.java
  src/main/java/com/x1/frans/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/x1/frans/approval/command/domain/repository/ApprovalLineCommandRepository.java
  src/main/java/com/x1/frans/approval/common/CommonResponse.java
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/exception/ApprovalActionFailedException.java
  src/main/java/com/x1/frans/exception/ApprovalLineNotFoundException.java
  src/main/java/com/x1/frans/exception/ApprovalNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
  src/main/resources/com/x1/frans/approval/query/repository/ApprovalQueryMapper.xml
Labels: ✨ Feature

#116 ✨ feat: SSE Emitter 구독 서비스 기능 구현
  src/main/java/com/x1/frans/exception/AllMessagesAlreadyReadException.java
  src/main/java/com/x1/frans/exception/NoDeletableMessagesException.java
  src/main/java/com/x1/frans/exception/NoPermissionOrNoneExist.java
  src/main/java/com/x1/frans/exception/UnreadMessagesCannotBeDeletedException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/notification/command/application/controller/NotificationController.java
  src/main/java/com/x1/frans/notification/command/application/scheduler/NotificationCleanupScheduler.java
  src/main/java/com/x1/frans/notification/command/application/service/NotificationService.java
  src/main/java/com/x1/frans/notification/command/domain/aggregate/Notification.java
  src/main/java/com/x1/frans/notification/command/domain/model/NotificationDomainType.java
  src/main/java/com/x1/frans/notification/command/domain/model/NotificationTarget.java
  src/main/java/com/x1/frans/notification/command/domain/model/NotificationType.java
  src/main/java/com/x1/frans/notification/command/domain/repository/EmitterRepository.java
  src/main/java/com/x1/frans/notification/command/domain/repository/EmitterRepositoryImpl.java
  src/main/java/com/x1/frans/notification/command/domain/repository/NotificationRepository.java
  src/main/java/com/x1/frans/notification/command/dto/NotificationDTO.java
Labels: ✨ Feature

#124 ✨ feat: 가맹점용 주문 등록 구현
  src/main/java/com/x1/frans/exception/InvalidRequestException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/command/application/controller/FranchiseOrderCommandController.java
  src/main/java/com/x1/frans/order/command/application/dto/FranchiseOrderCreateRequestDto.java
  src/main/java/com/x1/frans/order/command/application/dto/OrderMaterialRequestDto.java
  src/main/java/com/x1/frans/order/command/application/service/FranchiseOrderCommandService.java
  src/main/java/com/x1/frans/order/command/application/service/FranchiseOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/ProductOrder.java
  src/main/java/com/x1/frans/order/command/domain/repository/ProductOrderRepository.java
  src/main/java/com/x1/frans/product/query/controller/FranchiseProductQueryController.java
  src/main/java/com/x1/frans/product/query/dto/ProductListDTO.java
  src/main/resources/com/x1/frans/product/query/repository/ProductQueryMapper.xml
Labels: ✨ Feature

#137 ✨ feat: 결재본문 조회시 열람처리 기능 구현
  src/main/java/com/x1/frans/approval/command/domain/repository/ApprovalLineCommandRepository.java
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryServiceImpl.java
Labels: ✨ Feature

#139 🚑 fix: 주문 취소 수정, 본사용 주문 목록 조회 조건 수정
  src/main/java/com/x1/frans/order/command/application/service/FranchiseOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/order/command/application/util/OrderDeadlineUtils.java
  src/main/java/com/x1/frans/order/command/domain/aggregate/Order.java
  src/main/java/com/x1/frans/order/query/controller/FranchiseOrderQueryController.java
  src/main/java/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.java
  src/main/java/com/x1/frans/order/query/dto/OrderSearchConditionDto.java
  src/main/java/com/x1/frans/order/query/service/FranchiseOrderQueryService.java
  src/main/java/com/x1/frans/order/query/service/FranchiseOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/order/query/service/support/FranchiseAccessSupport.java
  src/main/java/com/x1/frans/order/query/service/support/OrderDetailCalculator.java
  src/main/java/com/x1/frans/order/query/service/support/OrderQuerySupport.java
  src/main/resources/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.xml
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
Labels: 🚑 Fix

#159 🔨refactor: 토큰에 서명 url 추가
  src/main/java/com/x1/frans/aws/service/AmazonS3Service.java
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/user/command/controller/UserCommandController.java
  src/main/java/com/x1/frans/user/command/repository/UserCommandRepository.java
  src/main/java/com/x1/frans/user/command/service/UserCommandService.java
  src/main/java/com/x1/frans/user/command/service/UserCommandServiceImpl.java
  src/main/java/com/x1/frans/user/command/vo/UpdateSignUrlRequestVO.java
Labels: ✨ Feature, 🔨 Refactor

#161 🚑 fix: 본사용 주문 목록 조회에서 접수 취소 상태 제외
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
Labels: 🚑 Fix

#164 ✨ feat: 결재목록 조회 기능 추가
  src/main/java/com/x1/frans/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/x1/frans/approval/query/dto/ApprovalListDTO.java
  src/main/java/com/x1/frans/approval/query/dto/ApprovalListLineDTO.java
  src/main/java/com/x1/frans/approval/query/repository/ApprovalQueryMapper.java
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryService.java
  src/main/java/com/x1/frans/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/java/com/x1/frans/notification/command/domain/repository/NotificationRepository.java
  src/main/resources/com/x1/frans/approval/query/repository/ApprovalQueryMapper.xml
Labels: ✨ Feature

#171 🔨 fix: profile 타입 추가
  src/main/java/com/x1/frans/aws/service/AmazonS3Service.java
Labels: ✨ Feature

#174 ✨ feat: 구매 요청 상태 변경 기능 구현
  src/main/java/com/x1/frans/purchase/command/application/controller/PurchaseRequestCommandController.java
  src/main/java/com/x1/frans/purchase/command/application/service/PurchaseRequestCommandService.java
  src/main/java/com/x1/frans/purchase/command/application/service/PurchaseRequestCommandServiceImpl.java
Labels: ✨ Feature

#177 ✨ feat: 자재 목록 조회에 이름 추가
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/product/query/dto/ProductDetailDTO.java
  src/main/resources/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.xml
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
Labels: ✨ Feature

#178 ✨ feat: github actions 설정 추가
  .github/workflow/cr.yml
Labels: ✨ Feature

#179 🚑 fix: workflows 디렉토리명 수정
  .github/workflows/cr.yml
  src/test/java/com/x1/frans/FransApplicationTests.java
  src/test/java/com/x1/frans/security/config/JwtTestConfig.java
Labels: 🚑 Fix

#180 🔨 refactor: 주문량 통계 조회 DTO 및 resultMap 수정
  src/main/java/com/x1/frans/statistics/query/view/dto/FranchiseOrderAmountQueryDTO.java
  src/main/java/com/x1/frans/statistics/query/view/dto/FranchiseReturnProductQueryDTO.java
  src/main/resources/com/x1/frans/statistics/query/view/repository/FranchiseOrderAmountMapper.xml
  src/main/resources/com/x1/frans/statistics/query/view/repository/FranchiseReturnProductMapper.xml
Labels: 🔨 Refactor

#194 ✨ feat: 발주 임시저장 등록,수정/발주 등록, 삭제, 취소/발주 상태 변경/구매 요청 상태 변경/발주 임시저장 목록 조회
  src/main/java/com/x1/frans/exception/CannotCancelPurchaseOrderException.java
  src/main/java/com/x1/frans/exception/CannotDeleteOrderException.java
  src/main/java/com/x1/frans/exception/InvalidOrderStatusException.java
  src/main/java/com/x1/frans/exception/InvalidPurchaseRequestProductException.java
  src/main/java/com/x1/frans/exception/ProductSupplierMisMatchException.java
  src/main/java/com/x1/frans/exception/PurchaseOrderNotFoundException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/purchase/command/domain/repository/PurchaseRequestProductRepository.java
  src/main/java/com/x1/frans/purchaseorder/command/application/controller/PurchaseOrderCommandController.java
  src/main/java/com/x1/frans/purchaseorder/command/application/dto/PurchaseOrderProductCreateDto.java
  src/main/java/com/x1/frans/purchaseorder/command/application/dto/PurchaseOrderProductUpdateDto.java
  src/main/java/com/x1/frans/purchaseorder/command/application/dto/PurchaseOrderSaveRequestDto.java
  src/main/java/com/x1/frans/purchaseorder/command/application/dto/PurchaseOrderStatusUpdateRequestDto.java
  src/main/java/com/x1/frans/purchaseorder/command/application/dto/PurchaseOrderUpdateRequestDto.java
  src/main/java/com/x1/frans/purchaseorder/command/application/service/PurchaseOrderCommandService.java
  src/main/java/com/x1/frans/purchaseorder/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/java/com/x1/frans/purchaseorder/command/domain/aggregate/PurchaseOrderEntity.java
  src/main/java/com/x1/frans/purchaseorder/command/domain/aggregate/PurchaseOrderProductEntity.java
  src/main/java/com/x1/frans/purchaseorder/command/domain/repository/PurchaseOrderRepository.java
  src/main/java/com/x1/frans/purchaseorder/enums/PurchaseOrderStatus.java
  src/main/java/com/x1/frans/purchaseorder/enums/PurchaseOrderStatusConverter.java
  src/main/java/com/x1/frans/purchaseorder/query/controller/PurchaseOrderQueryController.java
  src/main/java/com/x1/frans/purchaseorder/query/dto/PurchaseOrderDraftDetailDto.java
  src/main/java/com/x1/frans/purchaseorder/query/dto/PurchaseOrderDraftListDto.java
  src/main/java/com/x1/frans/purchaseorder/query/dto/PurchaseOrderProductDraftDto.java
  src/main/java/com/x1/frans/purchaseorder/query/repository/PurchaseOrderQueryMapper.java
  src/main/java/com/x1/frans/purchaseorder/query/service/PurchaseOrderQueryService.java
  src/main/resources/com/x1/frans/purchaseorder/query/repository/PurchaseOrderQueryMapper.xml
Labels: ✨ Feature

#198 ✨ feat: 납품서 조회, 납품 확정일 등록, 납품서 수정 기능 구현
  src/main/java/com/x1/frans/exception/CannotModifyDeliveryInfoException.java
  src/main/java/com/x1/frans/exception/NotFoundDeliveryInfoException.java
  src/main/java/com/x1/frans/exception/enums/EmptyDeliveryItemException.java
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/supplier/command/application/controller/HqDeliveryInfoController.java
  src/main/java/com/x1/frans/supplier/command/application/controller/SupplierDeliveryInfoCommandController.java
  src/main/java/com/x1/frans/supplier/command/application/dto/ConfirmDeliveryDateRequestDTO.java
  src/main/java/com/x1/frans/supplier/command/application/dto/DeliveryInfoCreateRequestDTO.java
  src/main/java/com/x1/frans/supplier/command/application/dto/DeliveryInfoModifyDTO.java
  src/main/java/com/x1/frans/supplier/command/application/service/HqDeliveryInfoService.java
  src/main/java/com/x1/frans/supplier/command/application/service/HqDeliveryInfoServiceImpl.java
  src/main/java/com/x1/frans/supplier/command/application/service/SupplierDeliveryInfoCommandService.java
  src/main/java/com/x1/frans/supplier/command/application/service/SupplierDeliveryInfoCommandServiceImpl.java
  src/main/java/com/x1/frans/supplier/command/domain/aggregate/SupplierDeliveryDetail.java
  src/main/java/com/x1/frans/supplier/command/domain/aggregate/SupplierDeliveryInfo.java
  src/main/java/com/x1/frans/supplier/command/domain/repository/HqDeliveryInfoRepository.java
  src/main/java/com/x1/frans/supplier/command/domain/repository/SupplierDeliveryDetailCommandRepository.java
  src/main/java/com/x1/frans/supplier/command/domain/repository/SupplierDeliveryInfoCommandRepository.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierDeliveryInfoQueryController.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierDeliveryProductQueryController.java
  src/main/java/com/x1/frans/supplier/query/dto/DeliveryDetailDTO.java
  src/main/java/com/x1/frans/supplier/query/dto/SupplierDeliveryInfoDTO.java
  src/main/java/com/x1/frans/supplier/query/dto/SupplierDeliveryProductDTO.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoMapper.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoQueryMapper.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierDeliveryProductMapper.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryInfoQueryService.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryInfoQueryServiceImpl.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryProductService.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryProductServiceImpl.java
  src/main/java/com/x1/frans/user/query/dto/LoginUserDTO.java
  src/main/resources/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoMapper.xml
  src/main/resources/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoQueryMapper.xml
  src/main/resources/com/x1/frans/supplier/query/repository/SupplierDeliveryProductMapper.xml
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: ✨ Feature

#201 ✨ feat: 로그인 시 필요한 정보 추가
  src/main/java/com/x1/frans/security/CustomUserDetails.java
  src/main/java/com/x1/frans/security/util/JwtUtil.java
  src/main/java/com/x1/frans/user/query/dto/LoginUserDTO.java
  src/main/resources/com/x1/frans/user/query/repository/UserQueryMapper.xml
Labels: ✨ Feature

#204 🔨 reafactor: JPA로 되어 있는 조회 mybatis로 수정
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestDetailDto.java
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestProductSimpleDto.java
  src/main/java/com/x1/frans/purchase/query/repository/PurchaseRequestQueryMapper.java
  src/main/java/com/x1/frans/purchase/query/repository/PurchaseRequestQueryRepository.java
  src/main/java/com/x1/frans/purchase/query/service/PurchaseRequestQueryService.java
  src/main/resources/com/x1/frans/purchase/query/repository/PurchaseRequestQueryMapper.xml
Labels: 🔨 Refactor

#206 ✨ feat: 구매 요청 조회 시 등록한 유저의 이름, 이메일도 조회되게 추가
  src/main/java/com/x1/frans/purchase/command/application/service/PurchaseRequestCommandServiceImpl.java
  src/main/java/com/x1/frans/purchase/command/domain/repository/PurchaseRequestMapper.java
  src/main/java/com/x1/frans/purchase/command/domain/repository/PurchaseRequestProductMapper.java
  src/main/java/com/x1/frans/purchase/query/controller/PurchaseRequestQueryController.java
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestDetailDto.java
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestSimpleDto.java
  src/main/java/com/x1/frans/purchase/query/repository/PurchaseRequestQueryMapper.java
  src/main/java/com/x1/frans/purchase/query/service/PurchaseRequestQueryService.java
  src/main/java/com/x1/frans/purchase/query/service/PurchaseRequestQueryServiceImpl.java
  src/main/java/com/x1/frans/purchaseorder/command/application/service/PurchaseOrderCommandServiceImpl.java
  src/main/resources/com/x1/frans/purchase/query/repository/PurchaseRequestQueryMapper.xml
Labels: ✨ Feature

#207 ✨ feat: 공급처가 납품해야 할 목록 및 상세 조회
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/supplier/query/controller/SupplierDeliveryInfoQueryController.java
  src/main/java/com/x1/frans/supplier/query/dto/DeliveryInfoDetailsDTO.java
  src/main/java/com/x1/frans/supplier/query/dto/PurchaseOrderProductDTO.java
  src/main/java/com/x1/frans/supplier/query/dto/RequestedDeliveryInfoDTO.java
  src/main/java/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoMapper.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryInfoQueryService.java
  src/main/java/com/x1/frans/supplier/query/service/SupplierDeliveryInfoQueryServiceImpl.java
  src/main/resources/com/x1/frans/supplier/query/repository/SupplierDeliveryInfoMapper.xml
Labels: ✨ Feature

#209 🔨 refactor: 자재 상세 조회에서도 사용여부 조회할 수 있도록 수정
  src/main/java/com/x1/frans/product/command/application/service/ProductCommandService.java
  src/main/java/com/x1/frans/product/command/application/service/dto/ProductCreateCommand.java
  src/main/java/com/x1/frans/product/command/application/service/dto/ProductUpdateCommand.java
  src/main/java/com/x1/frans/product/command/domain/aggregate/ProductEntity.java
  src/main/java/com/x1/frans/product/query/dto/ProductDetailDTO.java
  src/main/resources/com/x1/frans/product/query/repository/ProductQueryMapper.xml
Labels: 🔨 Refactor

#214 🚑 fix: hq, franchise 필터 관련 xml 수정
  src/main/resources/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.xml
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
Labels: 🚑 Fix

#215 🚑 fix: CORS 용 OPTIONS 요청 허용
  src/main/java/com/x1/frans/security/config/SecurityConfig.java
Labels: 🚑 Fix

#218 🔨 fix: 구매요청 상태로 조회 시 안되는 문제 수정
  src/main/java/com/x1/frans/purchase/query/service/PurchaseRequestQueryServiceImpl.java
Labels: 🚑 Fix

#222 🚑 fix: 배포 워크플로우 수정
  .github/workflows/cr.yml
Labels: 🚑 Fix

#225 🚑 fix: 배포 워크플로우 수정
  .github/workflows/cr.yml
Labels: 🚑 Fix

#228 🔨 refactor: unauthorized -> bad request
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
Labels: 🔨 Refactor

#229 🔨 fix: 구매요청 상세조회 문제 해결
  src/main/java/com/x1/frans/purchase/command/application/service/PurchaseRequestCommandServiceImpl.java
  src/main/java/com/x1/frans/purchase/command/application/service/dto/PurchaseRequestCreateCommand.java
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestDetailDto.java
  src/main/java/com/x1/frans/purchase/query/dto/PurchaseRequestProductSimpleDto.java
  src/main/resources/com/x1/frans/purchase/query/repository/PurchaseRequestQueryMapper.xml
Labels: 🚑 Fix

#231 🚑 fix: 반품 상세 정보 조회 매핑 오류 수정
  src/main/java/com/x1/frans/returns/query/dto/ReturnSearchConditionDTO.java
  src/main/resources/com/x1/frans/returns/query/repository/ReturnQueryMapper.xml
Labels: 🚑 Fix

#258 ✨ feat: 주문 마감 시간 조회 구현
  src/main/java/com/x1/frans/order/query/controller/HqOrderQueryController.java
  src/main/java/com/x1/frans/order/query/dao/HqOrderQueryMapper.java
  src/main/java/com/x1/frans/order/query/dto/OrderDeadlineResponseDto.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryService.java
  src/main/java/com/x1/frans/order/query/service/HqOrderQueryServiceImpl.java
  src/main/resources/com/x1/frans/order/query/dao/HqOrderQueryMapper.xml
Labels: ✨ Feature

#260 🚑 fix: 매핑 오류 해결
  src/main/resources/com/x1/frans/returns/query/repository/ReturnQueryMapper.xml
Labels: 🚑 Fix

#261 ✨ feat: 배포용 yml 파일 수정
  .github/workflows/cr.yml
Labels: 🚑 Fix

#270 🚑 fix: 커넥션 풀 사이즈 조정
  .github/workflows/cr.yml
Labels: 🚑 Fix

#272 🔨 refactor: 토큰 만료 상태 코드 변경
  src/main/java/com/x1/frans/exception/enums/ErrorCode.java
Labels: 🔨 Refactor

#280 ✨ feat: 가맹점에서 자재 목록 조회 구현
  src/main/java/com/x1/frans/config/SwaggerConfig.java
  src/main/java/com/x1/frans/product/query/controller/FranchiseProductQueryController.java
  src/main/java/com/x1/frans/product/query/dto/ProductListDTO.java
  src/main/resources/com/x1/frans/product/query/repository/ProductQueryMapper.xml
Labels: ✨ Feature

#281 ✨ feat: 반품 상태 변경 기능 구현
  src/main/java/com/x1/frans/order/command/domain/aggregate/Delivery.java
  src/main/java/com/x1/frans/order/command/domain/repository/DeliveryRepository.java
  src/main/java/com/x1/frans/returns/command/application/controller/HqReturnCommandController.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandService.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandServiceImpl.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnDetailEntity.java
  src/main/java/com/x1/frans/returns/command/domain/repository/ReturnDetailCommandRepository.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnDeliveriedAtVO.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnDeliveryInfoRequestVO.java
Labels: ✨ Feature

#288 ✨ feat: 반품 배송 정보 입력 기능 구현
  src/main/java/com/x1/frans/returns/command/application/controller/HqReturnCommandController.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandService.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandServiceImpl.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnCreateRequestVO.java
  src/main/java/com/x1/frans/returns/command/domain/vo/ReturnDeliveredAtVO.java
Labels: ✨ Feature

#292 🚑 fix: 반품 상태변경 오류 수정
  src/main/java/com/x1/frans/order/command/domain/aggregate/Delivery.java
  src/main/java/com/x1/frans/returns/command/application/controller/HqReturnCommandController.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandService.java
  src/main/java/com/x1/frans/returns/command/application/service/ReturnCommandServiceImpl.java
  src/main/java/com/x1/frans/returns/command/domain/aggregate/ReturnEntity.java
Labels: 🚑 Fix

#295 🚑 fix: 구매 단가를 판매 단가로 변경
  src/main/java/com/x1/frans/order/query/dto/ProductInTemplateDto.java
  src/main/resources/com/x1/frans/order/query/dao/FranchiseOrderQueryMapper.xml
Labels: 🚑 Fix

#299 🚑 fix: 자재 목록 조회에 공급처 id 추가
  src/main/java/com/x1/frans/product/query/controller/FranchiseProductQueryController.java
  src/main/java/com/x1/frans/product/query/controller/ProductQueryController.java
  src/main/java/com/x1/frans/product/query/dto/ProductListDTO.java
  src/main/java/com/x1/frans/product/query/repository/ProductQueryMapper.java
  src/main/java/com/x1/frans/product/query/service/ProductQueryService.java
  src/main/java/com/x1/frans/product/query/service/ProductQueryServiceImpl.java
  src/main/resources/com/x1/frans/product/query/repository/ProductQueryMapper.xml
Labels: 🚑 Fix
